### ISSUE TITLE
Create the lesson controller

### ISSUE THREAD

**Issue by Sese127** [Sese127/thp2#11]
### Why ?
Finally a controller so we can talk to the outer world \o/

We will use ActiveModel Serializer as it allows us to separate our concern. Its neither the role of a model nor a controller to take care of how to serialize as Json a model.

We will use Postman as a way to generate playable documentation and also to test manually our API.

Our API will be nicely constructed and will return nice errors and proper http response code.

### Must have
  - [ ] Serializer for lessons
  - [ ] Fully tested restful controller
  - [ ] Exported postman collection in `docs` directory
### Todo
**Serializer**
  - [ ] Add AMS (https://github.com/rails-api/active_model_serializers)
  - [ ] Do not configure it for now leave default settings
  - [ ] Add a new serializer for the model with id,title, description and created_at

**Controller**
  - [ ] Routing: resource must have everything but `new` and `edit`
  - [ ] Implement those using AMS to return json

**Test it with Postman**
https://www.getpost
